"""add refresh_token_hash and wp_sites

Revision ID: 59aeefb748f3
Revises: 20250921114618
Create Date: 2025-09-27 08:27:19.298105

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59aeefb748f3'
down_revision: Union[str, Sequence[str], None] = '20250921114618'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('refresh_token_hash', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'refresh_token_hash')
    # ### end Alembic commands ###
